[tools]
java = "temurin-21.0.12+101.0.LTS"

[env]
ANDROID_HOME = "{{env.HOME}}/Android/Sdk"
_.path = [
  "{{env.HOME}}/Android/Sdk/cmdline-tools/latest/bin",
  "{{env.HOME}}/Android/Sdk/platform-tools",
]
